{
 "title": "Token Holders & LPs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "version", "query": "*.*_*" },
   { "name": "build", "query": "*.*_*.*" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "token",
    "query": "walletProfileBot.$version.$build.token.*"
   },
   {
    "name": "holdersVal",
    "query": "walletProfileBot.$version.$build.token.$token.holders.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel $$token golders distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders_distribution.*, '$interval', 'avg', false), 6)"
    }
   ]
  },
  {
   "title": "$token holders distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(walletProfileBot.$version.$build.token.$token.holders_distribution.*, 6)"
    }
   ]
  },
  {
   "title": "$token pair LP count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "walletProfileBot.$version.$build.token.$token.pairLpCount"
    }
   ]
  },
  {
   "title": "$token holders count (bot)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "walletProfileBot.$version.$build.token.$token.holders_count.bot"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Price % and PairPrice since start ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairPriceChange, '$interval', 'avg', false), 4, 5)"
    },
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairPrice, '$interval', 'avg', false), 4, 5)"
    }
   ]
  },
  {
   "title": "$$token holders count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders_count.*, '$interval', 'avg', false), 5,6)"
    },
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders_posBalance, '$interval', 'avg', false), 5)"
    }
   ]
  },
  {
   "title": "$$token holders $holdersVal ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.*, '$interval', 'avg', false), 6, 7)"
    }
   ]
  },
  {
   "title": "pair LP Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairLpCount, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "token total liquiduty < 50m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.totalLiquidity, '$interval', 'avg', false), 50000000), 4)"
    }
   ]
  },
  {
   "title": "token trade volume usd ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.tradeVolumeUSD, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "pair reserve USD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairReserveUSD, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders count bot   < 1K",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.holders.count.bot, '$interval', 'avg', false), 1000), 2, 5)"
    }
   ]
  },
  {
   "title": "pair txCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairTxCount, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "pair past LP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairLpPast, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders avg current diversity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.curDiversityAvg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "pair volume USD > 1000",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.pairVolumeUSD, '$interval', 'avg', false), 1000), 4)"
    }
   ]
  },
  {
   "title": "pair price in pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.pairPrice, '$interval', 'avg', false), 100000), 4)"
    }
   ]
  },
  {
   "title": "pair reserve ETH",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairReserveETH, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders avg (in $holdersVal)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.avg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders MAX in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.max, '$interval', 'max', false), 4)"
    }
   ]
  },
  {
   "title": "holders count > 1K",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.holders.count.bot, '$interval', 'avg', false), 1000), 2, 5)"
    }
   ]
  },
  {
   "title": "token tx count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.txCount, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders median in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.med, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "Holders Age (nonce) Avarage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.nonce.avg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "pair total supply (constant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairTotalSupply, '$interval', 'avg', false), 4)"
    }
   ]
  }
 ]
}