{
 "title": "Token mon 2_1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "version", "query": "*.*_*" },
   { "name": "build", "query": "*.*_*.*" },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "token",
    "query": "walletProfileBot.$version.$build.token.*"
   },
   {
    "name": "holdersVal",
    "query": "walletProfileBot.$version.$build.token.$token.holders.*"
   }
  ]
 },
 "panels": [
  {
   "title": "UP price since start < 1000%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(currentAbove(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.pairPriceChange, '$interval', 'avg', false), 10), 0), 4)"
    }
   ]
  },
  {
   "title": "token trade volume usd > 10K",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.tradeVolumeUSD, '$interval', 'avg', false), 10000), 4)"
    }
   ]
  },
  {
   "title": "pair reserve USD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairReserveUSD, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "DOWN price since start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(currentBelow(summarize(walletProfileBot.$version.$build.token.$token.pairPriceChange, '$interval', 'avg', false), 0), 4)"
    }
   ]
  },
  {
   "title": "pair LP Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairLpCount, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "pair txCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairTxCount, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "pair past LP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairLpPast, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "token total liquiduty < 50m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.totalLiquidity, '$interval', 'avg', false), 50000000), 4)"
    }
   ]
  },
  {
   "title": "pair volume USD > 1000",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.pairVolumeUSD, '$interval', 'avg', false), 1000), 4)"
    }
   ]
  },
  {
   "title": "pair price in pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.pairPrice, '$interval', 'avg', false), 100000), 4)"
    }
   ]
  },
  {
   "title": "pair reserve ETH",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairReserveETH, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders count bot   < 1K",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.holders.count.bot, '$interval', 'avg', false), 1000), 2, 5)"
    }
   ]
  },
  {
   "title": "holders sum in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.sum, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders MAX in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.max, '$interval', 'max', false), 4)"
    }
   ]
  },
  {
   "title": "holders count > 1K",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.holders.count.bot, '$interval', 'avg', false), 1000), 2, 5)"
    }
   ]
  },
  {
   "title": "holders avg current diversity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.curDiversityAvg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders avg (in $holdersVal)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.avg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders median in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.med, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "Holders Age (nonce) Avarage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.nonce.avg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "price USD (ethPlorer)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.ethplorer.price.USD, '10m', 'sum', false), 4)"
    }
   ]
  },
  {
   "title": "token tx count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.txCount, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "bug/mega holders count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.megaCount, '$interval', 'max', false), 4)"
    }
   ]
  },
  {
   "title": "pair total supply (constant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairTotalSupply, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "chain transfers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(walletProfileBot.$version.$build.token.$token.transfers, '$interval', 'avg', false)"
    }
   ]
  },
  {
   "title": "Swap Count (over 100$ )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.swapCount, '$interval', 'sum', false), 0), 4)"
    },
    {
     "target": "walletProfileBot.$version.$build.token.$token.swapCount"
    }
   ]
  }
 ]
}