{
 "title": "Token Holders & LPs Influx",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "tag = \"version\"\nfrom(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [tag])\n  |> group()\n  |> distinct(column: tag)\n  |> limit(n: 10)\n  |> sort() "
   },
   {
    "name": "build",
    "query": "tag = \"build\"\nfrom(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [tag])\n  |> group()\n  |> distinct(column: tag)\n  |> limit(n: 10)\n  |> sort() "
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "token",
    "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"token\"))\n  |> keep(columns: [\"symbol\"])\n  |> group()\n  |> distinct(column: \"symbol\")\n  |> limit(n: 200)\n  |> sort()"
   },
   {
    "name": "holdersVal",
    "query": "from(bucket: \"walletProfileBot\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n    |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n    |> filter(fn:(r) => r._measurement == \"token\")\n    |> filter(fn:(r) =>r._field =~ /_std/)  \n    |> group(columns:[\"_field\"])\n    |> distinct(column:\"_field\")\n    |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "Holders distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /holders_distribution_*/)\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")        ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$token holder distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /holders_distribution_*/)\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$token LP count (bot)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")\n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pair_LpCount\")   \n  //|> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  //|> yield(name: \"mean\")\n  |>last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$token holders count (bot)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "  from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")\n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"_field\"] == \"holders_count_bot\")   \n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Price % and PairPrice since start ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pairPriceChange\" or r[\"_field\"] == \"pair_Price\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"build\"] == \"production\")\n  |> filter(fn: (r) => r[\"version\"] == \"2_5\")\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$$token holders score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")    \n  |> filter(fn: (r) => r[\"_field\"] =~ /score_/)    \n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")            ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$$token holders $holdersVal ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")    \n  |> filter(fn: (r) => r[\"_field\"] =~ /${holdersVal}/)    \n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")            ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$$token holders count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")  \n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")    \n  |> filter(fn: (r) => r[\"_field\"] == \"holders_count_bot\" or r[\"_field\"] == \"holders_count_ethplorer\" or r[\"_field\"] == \"holders_posBalance\")    \n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")          ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pair LP Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")\n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"${token}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pair_LpCount\")   \n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}