{
 "title": "Token All Influx",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "tag = \"version\"\nfrom(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [tag])\n  |> group()\n  |> distinct(column: tag)\n  |> limit(n: 10)\n  |> sort() "
   },
   {
    "name": "build",
    "query": "tag = \"build\"\nfrom(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [tag])\n  |> group()\n  |> distinct(column: tag)\n  |> limit(n: 10)\n  |> sort() "
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "token",
    "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"token\"))\n  |> keep(columns: [\"symbol\"])\n  |> group()\n  |> distinct(column: \"symbol\")\n  |> limit(n: 200)\n  |> sort()"
   },
   {
    "name": "holdersVal",
    "query": "from(bucket: \"walletProfileBot\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n    |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n    |> filter(fn:(r) => r._measurement == \"token\")\n    |> filter(fn:(r) =>r._field =~ /_std/)  \n    |> group(columns:[\"_field\"])\n    |> distinct(column:\"_field\")\n    |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "POS % price since start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")  \n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] =~ /${token:pipe}/)    \n  |> filter(fn: (r) => r[\"_field\"] == \"pairPriceChange\")\n  //|> filter(fn: (r) => r[\"_value\"] > 0 )\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")          ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "token trade volume usd ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")  \n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] =~ /${token:pipe}/)    \n  |> filter(fn: (r) => r[\"_field\"] == \"tradeVolumeUSD\")\n  |> filter(fn: (r) => r[\"_value\"] > 0 )\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")          ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pair reserve USD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")  \n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] =~ /${token:pipe}/)    \n  |> filter(fn: (r) => r[\"_field\"] == \"pair_ReserveUSD\")\n  |> filter(fn: (r) => r[\"_value\"] > 0 )\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")          ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NEGATIVE % price since start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")  \n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] =~ /${token:pipe}/)    \n  |> filter(fn: (r) => r[\"_field\"] == \"pairPriceChange\")\n  |> filter(fn: (r) => r[\"_value\"] < 0 )\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")          ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pair LP Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")  \n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] =~ /${token:pipe}/)    \n  |> filter(fn: (r) => r[\"_field\"] == \"pair_LpCount\")\n  //|> filter(fn: (r) => r[\"_value\"] > 0 )\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")          ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pair txCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"walletProfileBot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"app\"] == \"walletProfileBot\")  \n  |> filter(fn: (r) => r[\"build\"] == \"${build}\")\n  |> filter(fn: (r) => r[\"version\"] == \"${version}\")   \n  |> filter(fn: (r) => r[\"_measurement\"] == \"token\")\n  |> filter(fn: (r) => r[\"symbol\"] =~ /${token:pipe}/)    \n  |> filter(fn: (r) => r[\"_field\"] == \"pair_TxCount\")\n  //|> filter(fn: (r) => r[\"_value\"] > 0 )\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")          ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pair past LP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairLpPast, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "token total liquiduty < 50m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.totalLiquidity, '$interval', 'avg', false), 50000000), 4)"
    }
   ]
  },
  {
   "title": "pair volume USD > 1000",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.pairVolumeUSD, '$interval', 'avg', false), 1000), 4)"
    }
   ]
  },
  {
   "title": "pair price in pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.pairPrice, '$interval', 'avg', false), 100000), 4)"
    }
   ]
  },
  {
   "title": "pair reserve ETH",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairReserveETH, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders count bot   < 1K",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(walletProfileBot.$version.$build.token.$token.holders.count.bot, '$interval', 'avg', false), 1000), 4, 5)"
    }
   ]
  },
  {
   "title": "holders sum in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.sum, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders MAX in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.max, '$interval', 'max', false), 4)"
    }
   ]
  },
  {
   "title": "holders count > 1K",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.holders.count.bot, '$interval', 'avg', false), 1000), 4, 5)"
    }
   ]
  },
  {
   "title": "holders avg current diversity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.curDiversityAvg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders avg (in $holdersVal)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.avg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "holders median in $holdersVal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.$holdersVal.med, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "Holders Age (nonce) Avarage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.nonce.avg, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "price USD (ethPlorer)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.ethplorer.price.USD, '10m', 'sum', false), 4)"
    }
   ]
  },
  {
   "title": "token tx count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.txCount, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "bug/mega holders count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.holders.megaCount, '$interval', 'max', false), 4)"
    }
   ]
  },
  {
   "title": "pair total supply (constant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(walletProfileBot.$version.$build.token.$token.pairTotalSupply, '$interval', 'avg', false), 4)"
    }
   ]
  },
  {
   "title": "chain transfers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(walletProfileBot.$version.$build.token.$token.transfers, '$interval', 'avg', false)"
    }
   ]
  },
  {
   "title": "Swap Count (over 100$ )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(summarize(walletProfileBot.$version.$build.token.$token.swapCount, '$interval', 'sum', false), 0), 4)"
    },
    {
     "target": "walletProfileBot.$version.$build.token.$token.swapCount"
    }
   ]
  }
 ]
}